# Generated by Django 2.1.2 on 2019-02-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('bdate', models.DateTimeField(max_length=200)),
                ('is_blocked', models.BooleanField(max_length=200)),
                ('auth_key', models.CharField(max_length=200)),
            ],
        ),
    ]
