# Generated by Django 2.1.2 on 2019-02-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0002_auto_20190219_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, max_length=200),
        ),
    ]
