# Generated by Django 2.1.2 on 2019-02-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0003_auto_20190220_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
