# Generated by Django 2.1.2 on 2019-02-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0004_auto_20190220_2359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
    ]
