# Generated by Django 2.1.2 on 2019-02-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0005_auto_20190225_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='age',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
