# Generated by Django 2.1.2 on 2019-02-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0006_user1_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='initials',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
